version: "3"
services: 
    controller:
        build: .
        ports:
         - "8080:8080"
        depends_on:
         - mongo
         - redis
        networks:
         - my-network
    redis:
        image: "redis"
        ports: 
         - "6379:6379"
        networks:
         - my-network
    mongo:
        image: "mongo"
        ports:
         - "27017:27017"
        networks:
         - my-network
networks:
 my-network:

